# Generated by Django 5.0.3 on 2024-03-30 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StepOne',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('names', models.CharField(max_length=64)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StepThree',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contents', models.JSONField(default=None, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_3', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StepFour',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qn_number', models.IntegerField()),
                ('qn_type', models.CharField(max_length=255)),
                ('qn_labels_txt', models.CharField(default=None, max_length=255, null=True)),
                ('qn_labels_list', models.JSONField(default=None, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_4', to=settings.AUTH_USER_MODEL)),
                ('stepThree', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='step_3', to='answer_sheets.stepthree')),
            ],
        ),
        migrations.CreateModel(
            name='StepTwo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contents', models.JSONField(default=None, null=True)),
                ('stepOne', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='step_1', to='answer_sheets.stepone')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='stepthree',
            name='stepTwo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='step_2', to='answer_sheets.steptwo'),
        ),
    ]
