# Generated by Django 5.0.3 on 2024-03-31 18:57

import apps.answer_sheets.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer_sheets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stepone',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='steptwo',
            name='stepOne',
        ),
        migrations.RemoveField(
            model_name='stepthree',
            name='stepTwo',
        ),
        migrations.RemoveField(
            model_name='stepthree',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='steptwo',
            name='teacher',
        ),
        migrations.CreateModel(
            name='CustomSheet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('regdate', models.DateTimeField(default=apps.answer_sheets.models.dtime)),
                ('names', models.CharField(max_length=64)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HeaderBoxes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('regdate', models.DateTimeField(default=apps.answer_sheets.models.dtime)),
                ('contents', models.JSONField(default=None, null=True)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sheet_header', to='answer_sheets.customsheet')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('regdate', models.DateTimeField(default=apps.answer_sheets.models.dtime)),
                ('qn_number', models.IntegerField()),
                ('qn_type', models.CharField(max_length=255)),
                ('qn_labels_txt', models.CharField(default=None, max_length=255, null=True)),
                ('qn_labels_list', models.JSONField(default=None, null=True)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sheet_questions', to='answer_sheets.customsheet')),
            ],
        ),
        migrations.CreateModel(
            name='StudentKeys',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('regdate', models.DateTimeField(default=apps.answer_sheets.models.dtime)),
                ('contents', models.JSONField(default=None, null=True)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sheet_keys', to='answer_sheets.customsheet')),
            ],
        ),
        migrations.DeleteModel(
            name='StepFour',
        ),
        migrations.DeleteModel(
            name='StepOne',
        ),
        migrations.DeleteModel(
            name='StepThree',
        ),
        migrations.DeleteModel(
            name='StepTwo',
        ),
    ]
