# Generated by Django 5.0.3 on 2024-04-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer_sheets', '0002_remove_stepone_teacher_remove_steptwo_stepone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsheet',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
