# Generated by Django 5.0.3 on 2024-04-01 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answer_sheets', '0003_customsheet_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='qn_labels_list',
            new_name='questions',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='qn_labels_txt',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='qn_number',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='qn_type',
        ),
    ]
