# Generated by Django 5.0.3 on 2024-04-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer_sheets', '0005_questions_qn_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='qn_number',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
