# Generated by Django 5.0.3 on 2024-04-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer_sheets', '0006_questions_qn_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='show_labels',
            field=models.CharField(default=None, max_length=5, null=True),
        ),
    ]
