# Generated by Django 5.0.3 on 2024-04-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer_sheets', '0007_questions_show_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='show_labels',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
