# Generated by Django 5.0.3 on 2024-04-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer_sheets', '0008_alter_questions_show_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsheet',
            name='names',
            field=models.CharField(max_length=200),
        ),
    ]
