# Generated by Django 5.0.3 on 2024-05-06 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answer_sheets', '0009_alter_customsheet_names'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentKeys',
        ),
    ]
