# Generated by Django 5.0.3 on 2024-05-27 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answer_sheets', '0011_customsheet_heading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='show_labels',
        ),
    ]
