# Generated by Django 5.0.3 on 2024-05-27 15:02

import apps.answer_sheets.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer_sheets', '0012_remove_questions_show_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marking_scheme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('regdate', models.DateTimeField(default=apps.answer_sheets.models.dtime)),
                ('qn_number', models.IntegerField()),
                ('qn_options', models.CharField(max_length=200)),
                ('qn_indices', models.CharField(max_length=200)),
                ('qn_answer', models.CharField(default=None, max_length=200, null=True)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sheet_answers', to='answer_sheets.customsheet')),
            ],
        ),
    ]
