# Generated by Django 5.0.3 on 2024-05-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer_sheets', '0013_marking_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='marking_scheme',
            name='qn_marks',
            field=models.FloatField(default=None, null=True),
        ),
    ]
