# Generated by Django 5.0.3 on 2024-05-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer_sheets', '0015_marking_scheme_qn_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marking_scheme',
            name='qn_options',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
