# Generated by Django 5.0.3 on 2024-05-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer_sheets', '0016_alter_marking_scheme_qn_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsheet',
            name='circles_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customsheet',
            name='squares_count',
            field=models.IntegerField(default=0),
        ),
    ]
