# Generated by Django 5.0.3 on 2024-05-28 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answer_sheets', '0017_customsheet_circles_count_customsheet_squares_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeaderBoxes',
        ),
    ]
