# Generated by Django 5.0.3 on 2024-05-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer_sheets', '0018_delete_headerboxes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marking_scheme',
            name='qn_marks',
        ),
        migrations.AddField(
            model_name='questions',
            name='qn_marks',
            field=models.FloatField(default=1.0),
        ),
    ]
