# Generated by Django 5.0.3 on 2024-05-29 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer_sheets', '0019_remove_marking_scheme_qn_marks_questions_qn_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='marking_scheme',
            name='question',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='question_answers', to='answer_sheets.questions'),
        ),
    ]
