# Generated by Django 5.0.3 on 2024-06-09 22:41

import apps.students.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('regdate', models.DateTimeField(default=apps.students.models.dtime)),
                ('regnumber', models.CharField(max_length=200)),
                ('names', models.CharField(max_length=200)),
                ('year', models.IntegerField(default=None, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_program', to='classes.student_class')),
            ],
        ),
    ]
