# Generated by Django 5.0.3 on 2024-06-10 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='comment',
            field=models.TextField(default=None, null=True),
        ),
    ]
