# Generated by Django 5.0.3 on 2024-06-10 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_class',
            name='duration',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
