# Generated by Django 5.0.3 on 2024-06-02 10:33

import apps.exams.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('answer_sheets', '0020_marking_scheme_question'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('regdate', models.DateTimeField(default=apps.exams.models.dtime)),
                ('names', models.CharField(max_length=200)),
                ('published', models.BooleanField(default=False)),
                ('answersheet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_sheet', to='answer_sheets.customsheet')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
