# Generated by Django 5.0.3 on 2024-06-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='describe',
            field=models.TextField(default=None, null=True),
        ),
    ]
