# Generated by Django 5.0.3 on 2024-06-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_rename_published_exams_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='lastEdited',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
